pipeline {

    agent {
        node {
            label 'master'
        }
    }
   stages{      
    stage('Checkout code') {
        steps {
            checkout scm
        }
    }
       }
}
