pipeline {

    agent {
        node {
            label 'master'
        }
    }
   stages{      
    stage('Checkout code') {
        steps {
            checkout scm
        }
    }
           stage('Build code') {
        steps {
             
      sh "mvn clean install"
    
        }
    }
       }
}
